name: Automated API tests using Postman CLI

on: 
  workflow_dispatch:
  push:

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "21465020-28113d9c-4e28-424a-992e-13e2a762d260"
      - name: Logout
        run: echo -e "Yes\n" | postman logout ${{ secrets.POSTMAN_API_KEY }}
